# Design a simple Multi-Factor Authentication (MFA) System where a user first logs 
# in with a password, then verifies a one-time password (OTP) 
# generated by the system within a short time window — 
# all implemented in-memory without any database.

import hashlib, random, time, threading

class AuthSystem:
    def __init__(self):
        self.users = {}
        self.lock = threading.Lock()

    def hash_password(self, password):
        return hashlib.sha256(password.encode()).hexdigest()
    
    def register_user(self, username, password):
        with self.lock:
            if username in self.users:
                return "User already exists."
            self.users[username] = {"password_hash": self.hash_password(password), "otp": None, "otp_expiry": 0}
        return f" User '{username}' registered successfully."
    
    def login(self, username, password):
        with self.lock:
            user = self.users.get(username)
            if not user:
                return "User not found"
            if user["password_hash"] != self.hash_password(password):
                return "Invalid Password."
            
            otp = random.randint(100000, 999999)
            expiry = time.time() + 10
            user["otp"] = otp
            user["otp_expiry"] = expiry
        print(f"[SYSTEM] OTP for {username}: {otp} (valid 10s)")
        return "Password verified. OTP sent"
    
    def verify_otp(self, username, otp):
        with self.lock:
            user = self.users.get(username)
            if not user or user["otp"] is None:
                return "OTP not generated. Please login first."
            if time.time() > user["otp_expiry"]:
                return "OTP expired."
            if user["otp"] != otp:
                return "Invalid OTP."
        return f"Access Granted to {username}!"
    
if __name__ == "__main__":
    auth = AuthSystem()

    print(auth.register_user("bharadwaj", "secure123"))
    print(auth.login("bharadwaj", "secure123"))

    otp_input = int(input("Enter received OTP: "))  # Simulate user entering OTP
    print(auth.verify_otp("bharadwaj", otp_input))
            
    